### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ObservedObserver** [juandesant/DownloadSDSSFindingCharts#12]
When I run **sdssDR9findingChart objects.txt**, it shows:
```
Processing Sesame query for M31
Processing Sesame query for m82
Processing Sesame query for HCG89a
Processing Sesame query for HCG92c
Processing Sesame query for HCG7d
Processing Sesame query for HCG1
Processing Sesame query for tontoElQueLoLea
Processing Sesame query for HCG2
Processing Sesame query for CIG 96
Processing Sesame query for CIG 3
Traceback (most recent call last):
  File "/usr/local/bin/sdssDR9findingChart", line 349, in <module>
    result.get() # reraise exceptions of the remote call, if any
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IndexError: list index out of range

```

**Comment by nudomarinero** [comment]
I can confirm this error

**Comment by nudomarinero** [comment]
The query to Vizier for M31 with the address used returns the following:
```
# M31	#Q-00001
#! *** Nothing found *** 
Date: Mon, 30 Oct 2017 12:31:51 GMT
Server: Apache/2.2.15 (CentOS)
Connection: close
Content-Type: application/x-votable+xml
Content-Disposition: attachment; filename=vizier votable.vot
DocumentRef: VOTx35049
<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE version="1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#!Si=Simbad, all IDs (via url): -- VOTable description at http://www.ivoa.net/Documents/latest/VOT.html -->
<INFO ID="fatalError" name="Error" value="****Bad option -op"/>
<INFO name="Error" value="Bad option: -op"/>
</VOTABLE>': No known catalog could be found
Date: Mon, 30 Oct 2017 12:31:51 GMT
Server: Apache/2.2.15 (CentOS)
Connection: close
Content-Type: application/x-votable+xml
Content-Disposition: attachment; filename=vizier_votable.vot
DocumentRef: VOTx35049
<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE version="1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
<!-- VOTable description at http://www.ivoa.net/Documents/latest/VOT.html -->
<INFO ID="fatalError" name="Error" value="****Bad option -op"/>
<INFO name="Error" value="Bad option: -op"/>
</VOTABLE>'
!! 'HTTP/1.0 400 Incorrect request
Date: Mon, 30 Oct 2017 12:31:51 GMT
Server: Apache/2.2.15 (CentOS)
Connection: close
Content-Type: application/x-votable+xml
Content-Disposition: attachment; filename=vizier votable.vot
DocumentRef: VOTx35049
<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE version="1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
<!-- VOTable description at http://www.ivoa.net/Documents/latest/VOT.html -->
<INFO ID="fatalError" name="Error" value="****Bad option -op"/>
<INFO name="Error" value="Bad option: -op"/>
</VOTABLE>': No known catalog could be found

#!Vl=VizieR (local): No table found for: M31


#====Done (2017-Oct-30,22:25:37z)====
```
which is different to what was expected and may be causing the error
